// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sfuqepikohmqxcdzijfe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmdXFlcGlrb2htcXhjZHppamZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxODk2OTYsImV4cCI6MjA1OTc2NTY5Nn0.LqB0Hx59vXCp9P90VohnV2DwYbjFSNHwLM-9tGv3H7o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);